### PR TITLE
check the major version only for supported tracer versions

### PR DESCRIPTION
**Pull request by Setogit**
connect to strongloop-internal/scrum-nodeops#840

### CODE REVIEW

**Comment by Setogit** [comment]
@sl-node test please

**Comment by Setogit** [comment]
build fails on amazon-iojs-3 and ubuntu-iojs-3 due to Error: Cannot find module 'sqlite3'

**Comment by Setogit** [comment]
@sl-node test please

**Comment by rmg** [comment]
I don't understand all the implications, but it _looks_ like a trivial and relatively safe change.

LGTM.

**Pull request merged**
