### PR TITLE
Add PostgreSQL Support

### PR DESCRIPTION
**Pull request by Setogit**
connect to strongloop-internal/scrum-nodeops#1102

### CODE REVIEW

**Comment by Setogit** [comment]
@slnode test please

**Comment by Setogit** [comment]
@slnode test please

**Comment by Setogit** [comment]
@slnode test please

**Comment by kraman** [comment]
Its a big change but nothing stands out. LGTM

**Comment by Setogit** [comment]
i'd like to look into the Windows 5.0 build failure a bit before merge...

**Comment by Setogit** [comment]
One glaring different in the logs between Windows/Node4.0 vs. Windows/Node5.0 is the following.  Looks like we use C: drive for Win/4.0 build and D: drive for Win/5.0 build.  Difference is /jenkins is missing in the path:
    Win/4.0: CWD: C:/jenkins/workspace/minkelite/68dfec3a
    Win/5.0: CWD: D:/workspace/minkelite/ddb389d7

There are not many projects in IC building on Windows/Node 5.0.  One i found is strong-agent and i see the same pattern: strong-agent build fails on Win/Node 5.0 but succeeds on Win/Node 4.0 with similar CWD:
    Win/4.0: CWD: C:/jenkins/workspace/strong-agent/68dfec3a
    Win/5.0: CWD: D:/workspace/strong-agent/ddb389d7

Not clear yet whether that's the root cause of the Win/5.0 failure, but based on the observation, i don't feel i should hold the minkelite PR marge any further.

**Comment by Setogit** [comment]
Ryan commented that the difference in the paths is because the software set up is different between Win/Node 4 and Win/Node 5.

**Pull request merged**
